I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 8, in script
    scene bg_kage with dissolve(10.0)
TypeError: 'Dissolve' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 8, in script
    scene bg_kage with dissolve(10.0)
  File "/Users/afifsupianto/daigaku/smt_6/ges/renpy-8.3.7-sdk/renpy/ast.py", line 1374, in execute
    renpy.exports.with_statement(trans, paired=paired)
  File "/Users/afifsupianto/daigaku/smt_6/ges/renpy-8.3.7-sdk/renpy/exports/statementexports.py", line 257, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "/Users/afifsupianto/daigaku/smt_6/ges/renpy-8.3.7-sdk/renpy/display/core.py", line 1581, in do_with
    return self.interact(trans_pause=True,
  File "/Users/afifsupianto/daigaku/smt_6/ges/renpy-8.3.7-sdk/renpy/display/core.py", line 2218, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "/Users/afifsupianto/daigaku/smt_6/ges/renpy-8.3.7-sdk/renpy/display/core.py", line 2669, in interact_core
    trans = instantiate_transition(None, old_root, layers_root)
  File "/Users/afifsupianto/daigaku/smt_6/ges/renpy-8.3.7-sdk/renpy/display/core.py", line 2578, in instantiate_transition
    trans = self.ongoing_transition[layer](
TypeError: 'Dissolve' object is not callable

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.3.7.25031702
loan shark 1.0
Sun Apr 27 18:54:45 2025
